version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # TimescaleDB mit PostgreSQL 16
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # Neo4j database
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "user/password123"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  # MinIO as an S3-compatible storage solution
  minio:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z-cpuv1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # Redis with Redis Stack for vector database functionality
  redis:
    image: redis/redis-stack:7.4.0-v0
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web interface
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  postgres_data:
  neo4j_data:
  minio_data:
  redis_data:
  